### ISSUE TITLE
Spectrogram problems when obtaining data from IRIS for Ecuador Seismic Network

### ISSUE THREAD

**Issue by web-sys1** [liamtoney/sonify#8]
I'm welcome to be excited about this 'sonify' project. But when it comes to seismic networks in the world, the problem is mainly with the `EC` network ie ``EC.VCES..HHZ`` and Its location is `--`.

As you can see the screen should measure in color based on dB power, but it looks like the background is blue.

![vlcsnap-2022-02-23-19h20m55s385](https://user-images.githubusercontent.com/61905565/155372510-ae2b5f93-e8bf-49b4-9453-93fc5eb3b34c.png)

I'm getting a message like this:
``
 WARNING (norm_resp): computed and reported sensitivities differ by more than 5 percent.
         Execution continuing.
``

Here's the initial response from the station.

![BODE EC VCES HHZ 2012 234T00 00 01](https://user-images.githubusercontent.com/61905565/155373684-67d74278-51c6-4081-b9e9-1af320bc1cb2.png)

URL: [click here](https://service.iris.edu/irisws/evalresp/1/query?net=EC&sta=VCES&loc=--&cha=HHZ&time=2012-08-21T00:00:01&width=800&height=600&output=plot&annotate=true).

The code:
```python
from sonify import sonify
from obspy import UTCDateTime

sonify(
    network='EC',
    station='VCES',
    channel='HHZ',
    starttime=UTCDateTime('2022-02-10T14:40:40.430304Z'),
    endtime=UTCDateTime('2022-02-10T16:40:40.430304Z'),
    location='--',
    freqmin=1,
    freqmax=23,
    speed_up_factor=200,
    fps=1,  # Use fps=60 to ~recreate the JHEPC entry (slow to save!)
    spec_win_dur=8,
    db_lim=(-180, -130),
)
```

It's sensitivity is of ``3.14195E8 @ 1.0 Hz (SEED Stage 0)``

**Comment by web-sys1** [comment]
Even using `cmap='inferno'` the problem remains there in `sonify.py` source code.

![vlcsnap-2022-02-23-19h41m48s057](https://user-images.githubusercontent.com/61905565/155376635-cd0eb461-3c5c-4b01-96da-18eb4fe6dd41.png)

**Comment by liamtoney** [comment]
Hi @web-sys1, it looks like you're specifying the `db_lim` manually. Try using `db_lim=None` to allow _sonify_ to choose suitable colormap limits automatically.

<img width="2273" alt="Screen Shot 2022-02-23 at 8 55 31 AM" src="https://user-images.githubusercontent.com/38269494/155378380-a4967050-0c55-4b8f-9cf8-c0659910bbeb.png">

I took a look at the waveform processing and it looks like the response is being removed successfully.

**Comment by web-sys1** [comment]
@liamtoney
Thanks for telling me about it, but the question is still: why does the lower left `1e-6` appear?

Now it works, but I still get a `warning (norm_resp): computed and reported sensitivities differ by more than 5 percent. Execution continuing.`` Should I worry?

**Comment by liamtoney** [comment]
> @liamtoney Thanks for telling me about it, but the question is still: why does the `1e-6` appear on the lower left side?

That is the scaling value for the _y_-axis units. Meaning, the waveform ranges from about –0.000002 to +0.000002 µm/s.

> Now it works, but I still get a `warning (norm_resp): computed and reported sensitivities differ by more than 5 percent. Execution continuing.`` Should I worry?

That's a sensor response issue that's out of our control — I believe it means that what ObsPy computes as the scalar sensitivity from the full response is different from what the network operator provides as the scalar sensitivity. You'd have to contact the network manager to find out what's up with that.

I'm gonna go ahead and close this issue. If you find something new, don't hesitate to make a new one!
